version: "3.7"

services:
  musicboat:
    container_name: musicboat
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./cache:/home/node/musicboat/cache
